sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t shoaibcode/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shoaibcode/docker-react npm run test -- --coverage
  